# =============================================================================================================
# HYPRLAND By: Bangi
# =============================================================================================================
#
#
# Screen
#
# "Üres", automatikusan felismeri az eszköz kijelzőjét.
#
monitor = , preferred, auto, 1
#
#
# Input
#
# Magyar kiosztás.
#
input {
	kb_layout = hu
	follow_mouse = 1
}
#
#
# General
#
# Borderek, gapek mérete ablakok között
#
general {
	gaps_in = 5
	gaps_out = 10
	border_size = 2
	col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
	col.inactive_border = rgba(595959aa)
	layout = dwindle
}
#
#
# Decoration
#
# Ablak szélének kerekítése, elmosódás
#
decoration {
	rounding = 10
	blur {
		enabled = true
		size = 3
		passes = 1
	}
}
#
#
# Animation
#
# Alap animációk
# 
animations {
	enabled = true
	bezier = myBezier, 0.05, 0.9, 0.1, 1.05
	animation = windows, 1, 7, myBezier
	animation = workspaces, 1, 6, default
}
#
#
# Hotkeys
#
$mainMod = SUPER # WINDOWS gomb beállítása
bind = $mainMod, Return, exec, kitty # Win + Enter: Terminal
bind = $mainMod, B, exec, brave # Win + B: Brave
bind = $mainMod, Q, killactive, # Win + Q: Quit
bind = $mainMod, M, exit, # Win + M: Kilépés rendszerből
bind = $mainMod, V, togglefloating, # Win + V: Ablak kiemelése
bind = $mainMod, left, movefocus, l # Win + Bal nyíl: Bal oldali ablak fókuszálása
bind = $mainMod, right, movefocus, r # Win + Jobb nyíl: Jobb oldali ablak fókuszálása
bind = $mainMod, up, movefocus, u # Win + Fel nyíl: Fenti ablak fókuszálása
bind = $mainMod, down, movefocus, d # Win + Le nyíl: Lenti ablak fókuszálása
#
#
# Ecosystem
#
ecosystem {
	no_update_news = true
}
#
#
